"use client";
import { Proveedor } from "./store/provider";
import Link from "next/link";
export const metadata = {
  title: "Mi App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Proveedor>
        <body className={metadata.className}>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/service">Services</Link>
          <Link href="/contact">Contact</Link>
          {children}
        </body>
      </Proveedor>
    </html>
  );
}
